package awx

const credentialsAPIEndpoint = "/api/v2/credentials/"
const credentialInputSourceAPIEndpoint = "/api/v2/credential_input_sources/"
const credentialTypesAPIEndpoint = "/api/v2/credential_types/"
const executionEnvironmentsAPIEndpoint = "/api/v2/execution_environments/"
const groupsAPIEndpoint = "/api/v2/groups/"
const hostsAPIEndpoint = "/api/v2/hosts/"
const instanceGroupsAPIEndpoint = "/api/v2/instance_groups/"
const inventoriesAPIEndpoint = "/api/v2/inventories/"
const inventorySourcesAPIEndpoint = "/api/v2/inventory_sources/"
const jobTemplateAPIEndpoint = "/api/v2/job_templates/"
const jobAPIEndpoint = "/api/v2/jobs/"
const notificationTemplatesAPIEndpoint = "/api/v2/notification_templates/"
const organizationsAPIEndpoint = "/api/v2/organizations/"
const projectUpdatesAPIEndpoint = "/api/v2/project_updates/"
const projectsAPIEndpoint = "/api/v2/projects/"
const schedulesAPIEndpoint = "/api/v2/schedules/"
const settingsAPIEndpoint = "/api/v2/settings/"
const teamsAPIEndpoint = "/api/v2/teams/"
const usersAPIEndpoint = "/api/v2/users/"
const applicationAPIEndpoint = "/api/v2/applications/"
